# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='content',
            field=models.TextField(default='reply'),
            preserve_default=False,
        ),
    ]
